---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3

control_plane:
  hosts:
    k8s-control-plane-01:
      ansible_host: 192.168.73.40

worker_nodes:
  hosts:
    k8s-worker-01:
      ansible_host: 192.168.73.41
